#!/usr/bin/env python3
"""
Build prebuilt Sekinchan 1 Poly nutrient overlays for the dashboard.

Reads the 10m GeoTIFFs from the prediction folder and writes
development/js/sekinchan1poly_raster_overlays.js, defining:
  - RASTER_OVERLAYS_SEKINCHAN  : {nut: {dataUrl, bounds}}  (Leaflet imageOverlay)
  - RASTER_GRID_DATA_SEKINCHAN : {nut: {bounds, width, height, data}} (pixel sampling)

Colour ramps are imported from training_v3/predict_nutrients.py so the
prebuilt layers look identical to a live "Run Prediction" result.

Usage:
  python3 development/build_sekinchan_overlays.py [prediction_folder]
"""
import os
import sys
import io
import json
import base64

import numpy as np
import rasterio
import shapefile
from PIL import Image
from shapely.geometry import shape, Point
from shapely.ops import unary_union
from shapely.prepared import prep

DEV_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(DEV_DIR)
TRAINING_V3_DIR = os.path.join(ROOT_DIR, "training_v3")

DEFAULT_PRED_DIR = os.path.join(TRAINING_V3_DIR, "predictions_sekinchan1poly_2026-10-09_130535")
SHP_PATH = os.path.join(DEV_DIR, "boundaries", "sekinchan1poly.shp")
OUT_JS = os.path.join(DEV_DIR, "js", "sekinchan1poly_raster_overlays.js")

NUTRIENTS = ["N", "P", "K", "Mg", "Ca", "B"]

# Reuse the exact colour classes used by the live prediction pipeline
sys.path.insert(0, TRAINING_V3_DIR)
from predict_nutrients import COLOR_FUNCS  # noqa: E402


def load_polygon(shp_path):
    with shapefile.Reader(shp_path) as sf:
        geoms = [shape(s.__geo_interface__).buffer(0) for s in sf.shapes()]
    return prep(unary_union(geoms))


def main():
    pred_dir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PRED_DIR
    if not os.path.isdir(pred_dir):
        sys.exit(f"Prediction folder not found: {pred_dir}")

    poly = load_polygon(SHP_PATH)
    overlays, grids = {}, {}

    for nut in NUTRIENTS:
        tif = os.path.join(pred_dir, f"{nut}_nutrient_10m.tif")
        with rasterio.open(tif) as src:
            arr = src.read(1).astype(np.float32)
            b = src.bounds
            transform = src.transform
            h, w = arr.shape

        color_fn = COLOR_FUNCS[nut]
        grid = np.full((h, w), -9999.0, dtype=np.float32)
        rgba = np.zeros((h, w, 4), dtype=np.uint8)

        valid_px = 0
        for r in range(h):
            for c in range(w):
                v = arr[r, c]
                if not np.isfinite(v) or v <= 0:
                    continue
                lng, lat = transform * (c + 0.5, r + 0.5)  # pixel centre
                if not poly.contains(Point(lng, lat)):
                    continue
                grid[r, c] = round(float(v), 3)
                rgba[r, c] = color_fn(float(v))
                valid_px += 1

        img = Image.fromarray(rgba).resize((w * 4, h * 4), Image.Resampling.NEAREST)
        buf = io.BytesIO()
        img.save(buf, format="PNG")

        overlays[nut] = {
            "dataUrl": "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("utf-8"),
            "bounds": [[b.bottom, b.left], [b.top, b.right]],
        }
        grids[nut] = {
            "bounds": {"left": b.left, "bottom": b.bottom, "right": b.right, "top": b.top},
            "width": w,
            "height": h,
            "data": np.round(grid, 3).tolist(),
        }
        vals = grid[grid > 0]
        print(f"  ✓ {nut}: {w}x{h} grid, {valid_px} px in polygon, mean={vals.mean():.3f}")

    meta_path = os.path.join(pred_dir, "prediction_summary.json")
    meta = json.load(open(meta_path)) if os.path.isfile(meta_path) else {}

    js = (
        "// AUTO-GENERATED by build_sekinchan_overlays.py — do not edit by hand\n"
        f"// Source: {os.path.relpath(pred_dir, ROOT_DIR)}\n"
        f"const SEKINCHAN_PREDICTION_META = {json.dumps(meta)};\n"
        f"const RASTER_OVERLAYS_SEKINCHAN = {json.dumps(overlays)};\n"
        f"const RASTER_GRID_DATA_SEKINCHAN = {json.dumps(grids)};\n"
        "if (typeof window !== 'undefined') {\n"
        "    window.SEKINCHAN_PREDICTION_META = SEKINCHAN_PREDICTION_META;\n"
        "    window.RASTER_OVERLAYS_SEKINCHAN = RASTER_OVERLAYS_SEKINCHAN;\n"
        "    window.RASTER_GRID_DATA_SEKINCHAN = RASTER_GRID_DATA_SEKINCHAN;\n"
        "}\n"
    )
    with open(OUT_JS, "w") as f:
        f.write(js)
    print(f"\n✅ Wrote {OUT_JS} ({os.path.getsize(OUT_JS) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
