"""
convert_boundaries.py
Converts all .shp + .dbf pairs in ./boundaries/ into GeoJSON JS blocks
for embedding into REAL_MAPS_DATA in comprehensive.html / standard.html.
"""
import shapefile, json, os, sys

BOUNDARIES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'boundaries')

# Config: (key, filename_stem, display_name, name_field)
MAPS = [
    ('jengka24',        'Ladang Jengka 24',         'Ladang Jengka 24',       'block'),
    ('jengka25',        'Ladang Jengka 25',         'Ladang Jengka 25',       'Peringkat'),
    ('kota_gelanggi5',  'Ladang Kota Gelanggi 5',   'Ladang Kota Gelanggi 5','Peringkat'),
    ('ppptar',          'Ladang PPPTAR',             'Ladang PPPTAR',          'Peringkat'),
    ('geolocation_ish', 'GEOLOCATION_ISH_SPOC_A7',  'GEOLOCATION ISH SPOC A7','SPOC_NAME'),
    ('polygon_ish',     'POLYGON_ISH_SPOC_A7',      'POLYGON ISH SPOC A7',   'SPOC_NAME'),
    ('soil_series',     'SOIL_SERIES_SPOC_A7',      'SOIL SERIES SPOC A7',   'DESCR'),
]

SUPPRESS_FIELDS = {'Shape_Leng', 'Shape_Area', 'FCD_S', 'ARH'}

def shp_to_geojson(stem, display_name, name_field):
    path = os.path.join(BOUNDARIES_DIR, stem)
    with shapefile.Reader(path) as sf:
        fields = [f[0] for f in sf.fields[1:]]
        features = []
        for i, sr in enumerate(sf.shapeRecords()):
            geom = sr.shape.__geo_interface__
            rec = dict(zip(fields, sr.record))
            props = {}
            for k, v in rec.items():
                if isinstance(v, str):
                    v = v.strip()
                if isinstance(v, float) and (v != v):  # NaN check
                    v = None
                props[k] = v

            raw_name = None
            for candidate in [name_field, 'block', 'name', 'NAME', 'BLOCK', 'SPOC_NAME', 'DESCR', 'SMALLHOLDE']:
                if candidate in props and props[candidate] and str(props[candidate]).strip():
                    raw_name = str(props[candidate]).strip()
                    break
            props['name'] = raw_name if raw_name else f'Feature {i+1}'
            features.append({'type': 'Feature', 'geometry': geom, 'properties': props})

    return {'type': 'FeatureCollection', 'mapName': display_name, 'features': features}, fields

results = {}
tooltip_fields_map = {}

for key, stem, display_name, name_field in MAPS:
    try:
        fc, fields = shp_to_geojson(stem, display_name, name_field)
        results[key] = fc
        tooltip_fields_map[key] = [f for f in fields if f not in SUPPRESS_FIELDS and f != 'name']
        print(f'[OK] {display_name}: {len(fc["features"])} features', file=sys.stderr)
    except Exception as e:
        print(f'[ERROR] {stem}: {e}', file=sys.stderr)

# Write output file
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'boundaries_geojson.js')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED by convert_boundaries.py\n')
    f.write('// PASTE the REAL_MAPS_DATA block into comprehensive.html and standard.html\n\n')
    f.write('// ===== ADDITIONS TO REAL_MAPS_DATA =====\n')
    for key, stem, display_name, name_field in MAPS:
        if key in results:
            fc_json = json.dumps(results[key], separators=(',', ':'), ensure_ascii=False)
            f.write(f'            {key}: {fc_json},\n')
    f.write('\n// ===== TOOLTIP FIELDS PER MAP =====\n')
    f.write('const BOUNDARY_TOOLTIP_FIELDS = ' + json.dumps(tooltip_fields_map, indent=4, ensure_ascii=False) + ';\n')

print(f'Written to {out_path}', file=sys.stderr)
